version: '3.9'

services:

  jenkins:
    container_name: jenkins
    hostname: jenkins
    build: jenkins/.
    ports:
      - 8080:8080
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock