-- https://quickstarts.snowflake.com/guide/getting_started_iceberg_tables/index.html#1

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE WAREHOUSE DEMO_WH;
CREATE OR REPLACE ROLE DEMO_ROLE;
CREATE OR REPLACE DATABASE DEMO_DB;
CREATE OR REPLACE SCHEMA DEMO;
GRANT ALL ON DATABASE DEMO_DB TO ROLE DEMO_ROLE WITH GRANT OPTION;
GRANT ALL ON SCHEMA DEMO_DB.DEMO TO ROLE DEMO_ROLE WITH GRANT OPTION;;
GRANT ALL ON WAREHOUSE DEMO_WH TO ROLE DEMO_ROLE WITH GRANT OPTION;;

CREATE OR REPLACE USER DEMO_USER
    PASSWORD='password',
    LOGIN_NAME='DEMO_USER',
    MUST_CHANGE_PASSWORD=FALSE,
    DISABLED=FALSE,
    DEFAULT_WAREHOUSE='DEMO_WH',
    DEFAULT_ROLE='DEMO_ROLE';

GRANT ROLE DEMO_ROLE TO USER DEMO_USER;
GRANT ROLE DEMO_ROLE TO USER USERNAME;
GRANT ROLE accountadmin TO USER DEMO_USER;
